### ISSUE TITLE
Error Compiled

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/mod-azerothshard#16]
Erro	C1083	Não é possível abrir arquivo incluir: 'AZTH.h': No such file or directory	scripts	C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3_SC.cpp	14

Erro	C2882	'ObjectAccessor': uso inválido de identificador de namespace em expressão	scripts	C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3.cpp	175
	
Erro	C2440	'inicializando': não é possível converter de 'GuidSet *' para 'std::set<uint64,std::less<uint64>,std::allocator<uint64>> *'	scripts
C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3.cpp	221	

Erro	C2882	'ObjectAccessor': uso inválido de identificador de namespace em expressão	scripts	C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3.cpp	224	

Erro	C2440	'inicializando': não é possível converter de 'const ObjectGuid' para 'uint64'	scripts	C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3.cpp	296	

Erro	C2882	'ObjectAccessor': uso inválido de identificador de namespace em expressão	scripts	C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3.cpp	297	

Erro	C2660	'ArenaTeam::CreateTempArenaTeam': função não recebe 4 argumentos	scripts	C:\Server\AzerothCore\Core\modules\mod-Arena-Solo-3v3\src\Solo3v3.cpp	310

**Comment by pangolp** [comment]
Hello, I am working on a pull request to correct the bugs, and to compile with the latest version of the emulator. However, I have not tested the modules 1 by 1, I was only in charge of checking for errors and avoiding compilation problems. After this issue is resolved, the idea is to receive reports of the failures and see if we can repair them, as the reports are generated. Greetings.
