### ISSUE TITLE
AutoBalance.h Compile Error Fixed

### ISSUE THREAD

**Issue by MiniFexx** [azerothcore/mod-azerothshard#20]
Code: C1083 Data (Include) cannot be open: "AutoBalance.h": No such file or directory

Anyone have a clue, how to fix this issue? 

Compile error fixed (AutoBalance.h was missing)

**Comment by pangolp** [comment]
Hello, I am working on a pull request to correct the bugs, and to compile with the latest version of the emulator. However, I have not tested the modules 1 by 1, I was only in charge of checking for errors and avoiding compilation problems. After this issue is resolved, the idea is to receive reports of the failures and see if we can repair them, as the reports are generated. Greetings.
