### ISSUE TITLE
Missing DB Table

### ISSUE THREAD

**Issue by LordArcanine** [azerothcore/mod-azerothshard#21]
i installed the mod-azerothshard
i installed all the dbs but it give me a error, says the table guildhouses_add dont exist, but i cant find the sql for it.
the worldserver give the error and after that a segmentation fault

Compiled on lastest az

**Comment by pangolp** [comment]
Hello, I am working on a pull request to correct the bugs, and to compile with the latest version of the emulator. However, I have not tested the modules 1 by 1, I was only in charge of checking for errors and avoiding compilation problems. After this issue is resolved, the idea is to receive reports of the failures and see if we can repair them, as the reports are generated. Greetings.
